DROP DATABASE IF EXISTS anniversaries;
CREATE DATABASE IF NOT EXISTS anniversaries DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
USE anniversaries;

DROP TABLE IF EXISTS ANNIVERSARY;
CREATE TABLE IF NOT EXISTS ANNIVERSARY (
  ANNIVERSARYID int(11) NOT NULL AUTO_INCREMENT,
  MODERNGIFT varchar(30) NOT NULL,
  TRADGIFT varchar(30) NOT NULL,
  PRIMARY KEY (ANNIVERSARYID)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8;

INSERT INTO ANNIVERSARY (ANNIVERSARYID, MODERNGIFT, TRADGIFT) VALUES
(1, 'Clocks', 'Paper'),
(2, 'China', 'Cotton'),
(3, 'Glass/Crystal', 'Leather');

DROP TABLE IF EXISTS PLACE;
CREATE TABLE IF NOT EXISTS PLACE (
  PLACEID int(11) NOT NULL AUTO_INCREMENT,
  PLACENAME varchar(30) NOT NULL,
  COUNTRY varchar(30) NOT NULL,
  ANNIVERSARYID int(11) NOT NULL,
  PRIMARY KEY (PLACEID)
) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=utf8;

INSERT INTO PLACE (PLACEID, PLACENAME, COUNTRY, ANNIVERSARYID) VALUES
(1, 'Paris', 'France', 1),
(2, 'London', 'England', 1),
(3, 'Manchester', 'England', 1),
(4, 'Barcelona', 'Spain', 2),
(5, 'Girona', 'Spain', 2),
(6, 'New York', 'USA', 3);

ALTER TABLE PLACE
  ADD CONSTRAINT PLACE_ibfk_1 FOREIGN KEY (ANNIVERSARYID) REFERENCES ANNIVERSARY (ANNIVERSARYID);
  
DELIMITER $$
--
-- Procedures
--
DROP PROCEDURE IF EXISTS `AddAnniversary`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `AddAnniversary` (IN `inModernGift` TEXT, IN `inTradGift` TEXT)  BEGIN
 INSERT INTO ANNIVERSARY (MODERNGIFT, TRADGIFT)
        VALUES (inModernGift, inTradGift);
END$$

DROP PROCEDURE IF EXISTS `AddPlace`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `AddPlace` (IN `inPlaceName` TEXT, IN `inCountry` TEXT, IN `inAnniversaryId` INT)  BEGIN
 INSERT INTO PLACE (PLACENAME, COUNTRY, ANNIVERSARYID)
        VALUES (inPlaceName, inCountry, inAnniversaryId);
END$$

DROP PROCEDURE IF EXISTS `GetAnniversary`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `GetAnniversary` (IN `inAnniversaryId` INT)  BEGIN
 SELECT *
 FROM     ANNIVERSARY
 WHERE  ANNIVERSARYID = inAnniversaryId ;
END$$

DROP PROCEDURE IF EXISTS `GetAnniversaries`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `GetAnniversaries` ()  READS SQL DATA
BEGIN
  Select ANNIVERSARYID, MODERNGIFT, TRADGIFT From ANNIVERSARY Order By ANNIVERSARYID;    
END$$

DROP PROCEDURE IF EXISTS `GetAnniversaryPlaces`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `GetAnniversaryPlaces` (IN `inAnniversaryId` INT)  NO SQL
BEGIN
  SELECT PLACEID, PLACENAME, COUNTRY FROM PLACE
  WHERE ANNIVERSARYID = inAnniversaryId 
  Order By PLACENAME;
End$$

DELIMITER ;  

